### PR TITLE
Add Dark Mode support

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by sniklaus** [comment]
Thank you for your contribution! It seems incomplete as shown in the screenshot below?

image

**Comment by TotalCaesar659** [comment]
When I load the source code into Firefox after `git clone`, it shows this:

How can I get the result like on your screenshot?

**Comment by sniklaus** [comment]
The easiest is to just go to the page and edit it on the fly.

https://user-images.githubusercontent.com/1238034/213966758-b555b255-f87c-4af9-be45-b899df805589.mp4

**Comment by TotalCaesar659** [comment]
Ah, I got it. I downloaded XPI file and unpacked it, and there are **bootstrap.css** that controls page design (it's not uploaded to this repo on Github, as **jquery.js**, **moment.js** and even **icon.png**). Because it's not here, I can't add any more changes.

**Comment by sniklaus** [comment]
No worries, I'll close this pull request then due to it being incomplete. Should you want to revisit this again, either by trying the changes directly like shown in the video or copying over the missing files from the XPI (they are missing from this repository since they are just external libraries), then don't hesitate to open up another pull request. :+1:

**Pull request closed without merging**
